<?php

namespace app\controllers;

use Yii;
use app\models\Advertiser;
use app\models\AdvertiserrSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

class MyController extends SiteController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        echo "<br>";
        echo "<br>";

        echo "<br>";
        echo "<br>";

        $var1 = 'Bob';
        $var = 'Joe';
        $var = &$var1;
        echo "$var, $var, $var1";
        echo '<br>';

        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }

}